drop table ORDER_LINE;
drop table ORDERS;
drop table PRODUCT_DEFINITION;
drop table MANUFACTURER;
drop table SHIPPING;
drop table CUSTOMER;
drop table SEQUENCE;


create table SEQUENCE (
  SEQ_NAME VARCHAR(40) NOT NULL CONSTRAINT SEQUENCE_PK PRIMARY KEY,
  SEQ_COUNT INT NOT NULL
);

create table SHIPPING (
  ID INT NOT NULL CONSTRAINT SHIPPING_METHOD_PK PRIMARY KEY,
  NAME VARCHAR(40) NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL,
  PRICE NUMERIC (5,2) NOT NULL,
  CURRENCY_CODE CHAR(3) NOT NULL,
  SHIPPING_METHOD INT NOT NULL
);

create table CUSTOMER (
  ID INT NOT NULL CONSTRAINT CUSTOMER_PK PRIMARY KEY,
  FIRST_NAME VARCHAR(40) NOT NULL,
  LAST_NAME VARCHAR(40) NOT NULL,
  ADDRESS_LINE VARCHAR(100) NOT NULL,
  CITY VARCHAR(40) NOT NULL,
  STATE VARCHAR(40) NOT NULL,
  ZIP_CODE VARCHAR(40) NOT NULL,
  EMAIL_ADDRESS VARCHAR(40) NOT NULL
);

create table MANUFACTURER (
  ID INT NOT NULL CONSTRAINT MANUFACTURER_PK PRIMARY KEY,
  NAME VARCHAR(40) NOT NULL
);

create table PRODUCT_DEFINITION (
  ID INT NOT NULL CONSTRAINT PRODUCT_DEFINITION_PK PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  PACKAGE VARCHAR(40) NOT NULL,
  DESCRIPTION VARCHAR(400) NOT NULL,
  CATEGORY INT NOT NULL,
  PRICE NUMERIC (5,2) NOT NULL,
  CURRENCY_CODE CHAR(3) NOT NULL,
  MANUFACTURER_ID INT NOT NULL CONSTRAINT PRODUCT_DEF_MANUFACTURER_FK REFERENCES MANUFACTURER
);

create table ORDERS (
  ID INT NOT NULL CONSTRAINT ORDER_PK PRIMARY KEY,
  CREATION_DT TIMESTAMP NOT NULL,
  CUSTOMER_ID INT NOT NULL CONSTRAINT ORDER_CUSTOMER_FK REFERENCES CUSTOMER,
  SHIPPING_ID INT NOT NULL CONSTRAINT ORDER_SHIPPING_FK REFERENCES SHIPPING
);

create table ORDER_LINE (
  ID INT NOT NULL CONSTRAINT ORDER_LINE_PK PRIMARY KEY,
  QUANTITY INT NOT NULL,
  PRICE NUMERIC(6,2) NOT NULL,
  CURRENCY_CODE CHAR(3) NOT NULL,
  PRODUCT_ID INT NOT NULL CONSTRAINT PRODUCT_DEF_ORDER_LINE_FK REFERENCES PRODUCT_DEFINITION,
  ORDER_ID INT NOT NULL CONSTRAINT ORDER_LINE_ORDER_FK REFERENCES ORDERS
);

create table INVENTORY (
  PRODUCT_ID INT NOT NULL CONSTRAINT INVENTORY_PK PRIMARY KEY,
  INVENTORY INT NOT NULL
);

insert into SEQUENCE(SEQ_NAME, SEQ_COUNT)
VALUES('SEQ_GEN', 1);

insert into Shipping (ID, NAME, DESCRIPTION, PRICE, CURRENCY_CODE, SHIPPING_METHOD)
values(1, 'Freight Movers', 'Freight Movers bla bla', 7.5, 'EUR', 0)
, (2, 'International Shipping', 'International Shipping bla bla', 12.25, 'EUR', 1);

